const iconImage = {
    exercise: 'today_card_icon_exercise',
    audioExercise: 'icon_audiostory_home',
    letterIcon: 'today_card_icon_letter',
    thoughtIcon: 'today_card_icon_thought_control',
    protectIcon: 'img_pornblocker',
    sleepIcon: 'img_sleepicon',
    BrainIcon: 'today_card_icon_brain_training',
    pathIcon: 'today_card_icon_choice',
    storyCardIcon: 'today_card_icon_story',
    videoIcon: 'today_card_icon_video',
    visualizationIcon: 'today_card_icon_imagine',
    activityIcon: 'icon_week4',
    DidyouknowIcon: 'today_card_icon_fact',
    BreathingIcon: 'today_card_icon_breathing',
    StressIcon: 'today_card_icon_zen',
    KegalIcon: 'today_card_icon_kegals',
    morningIcon: 'today_card_icon_morning',
    EmotionalIcon: 'today_card_icon_emotion',
    MeditationIcon: 'today_card_icon_meditation',
    FaithIcon: 'today_card_icon_faith',
    JournalIcon: 'today_card_icon_journal',
    rThoughtControl: 'today_icon_circle_thought_control',
    rChoosePath: 'img_motivation',
    rVisualize: 'today_icon_circle_visualize',
    rMeditation: 'icon_meditation_home',
    rStress: 'today_icon_circle_stress_relief',
    rStory: 'today_icon_circle_story',
    tMotivation: 'img_motivation',
    rEmotional: 'today_icon_circle_emotion',
    rBrainTraining: 'icon_exercise_home',
    rAboutYou: 'icon_aboutyou_home',
    rGameYou: 'img_game',
    notificationIcon: 'today_card_icon_notifications',
    monthlyIcons: [
        'today_challenge_card_icon_jan',
        'today_challenge_card_icon_feb',
        'today_challenge_card_icon_mar',
        'today_challenge_card_icon_apr',
        'today_challenge_card_icon_may',
        'today_challenge_card_icon_jun',
        'today_challenge_card_icon_jul',
        'today_challenge_card_icon_aug',
        'today_challenge_card_icon_sep',
        'today_challenge_card_icon_oct',
        'today_challenge_card_icon_nov',
        'today_challenge_card_icon_dec'],
    writeAboutYourDayIcon: 'card_icon_journal_small',
    rewiringIcon: 'icon_all',
    iconLevelIcon: 'icon_level',
    iconAwardIcon: 'icon_award',
    iconDaysIcon: 'icon_days',
    iconVictoryIcon: 'icon_victory',
};

const notificationList = {
    checkUpNotification: {
        Icon: iconImage.iconVictoryIcon,
        title: "Checkup Now",
        desc: "You missed your checkup yesterday",
        pageName: 'calendar',
        improve: [{"awards_selfconfident": 1}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
        type: [
            {
                title: 'Checkup Now',
                typeBG: '#9551FF',
            },
        ]
    },
    checkUpCalendarUpdate: {
        Icon: iconImage.iconVictoryIcon,
        title: "Welcome back",
        desc: "Take your previous days checkup",
        pageName: 'missedcalendar',//missedcalendar
        improve: [{"awards_selfconfident": 1}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
        type: [
            {
                title: 'Checkup Now',
                typeBG: '#9551FF',
            },
            {
                title: 'Update Calendar',
                typeBG: '#9551FF',
            },
        ]
    },
    newUserCalendar: {
        Icon: iconImage.iconVictoryIcon,
        title: "Welcome back",
        desc: "Take Your Previous Days Checkin",
        pageName: 'updatecalendar',
        improve: [{"awards_selfconfident": 1}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
        type: [
            {
                title: 'Update Calendar',
                typeBG: '#9551FF',
            },
        ]
    },
    streakGoal: {
        Icon: iconImage.iconDaysIcon,
        title: "WellDone",
        desc: "",
        pageName: 'days',
        improve: [{"awards_selfconfident": 1}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
        type: [
            {
                title: 'Preview',
                typeBG: '#9551FF',
            },
            {
                title: 'Cancel',
                typeBG: 'gray',
            },
        ]
    },
    rewiringTotal: {
        Icon: iconImage.rewiringIcon,
        title: "Congratulation",
        desc: "",
        pageName: 'rewiring',
        improve: [{"awards_selfconfident": 1}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
        type: [
            {
                title: 'Preview',
                typeBG: '#9551FF',
            },
            {
                title: 'Cancel',
                typeBG: 'gray',
            },
        ]
    },
    levelIncrease: {
        Icon: iconImage.iconLevelIcon,
        title: "Congratulation",
        desc: "",
        pageName: 'level',
        improve: [{"awards_selfconfident": 1}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
        type: [
            {
                title: 'Preview',
                typeBG: '#9551FF',
            },
            {
                title: 'Cancel',
                typeBG: 'gray',
            },
        ]
    },
    reachAward: {
        Icon: iconImage.iconAwardIcon,
        title: "Excellent",
        desc: "",
        pageName: 'award',
        improve: [{"awards_selfconfident": 1}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
        type: [
            {
                title: 'Preview',
                typeBG: '#9551FF',
            },
            {
                title: 'Cancel',
                typeBG: 'gray',
            },
        ]
    },
    checkInTime: {
        Icon: 'icon_victory',
        title: "Let's time for your Rate Your Day",
        desc: "You have sedule 6pm",
        pageName: 'checkin',
        improve: [{"awards_selfconfident": 1}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
        type: [
            {
                title: 'CheckUp',
                typeBG: '#9551FF',
            },
            {
                title: 'Reschedule checkup time',
                typeBG: '#9551FF',
            },
        ]
    },
};

const allOptionalExercies = {
    healthyActivity: {
        Icon: iconImage.activityIcon,
        title: "To-Do Activity",
        desc: "Try to finish every today activity",
        pageName: 'healthyActivity',
        improve: [{"awards_selfconfident": 1}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#ec6367',
        gradientEnd: '#f08e4c',
        backgroundColor: '#ED6058',
    },
    breathingActivity: {
        Icon: iconImage.rMeditation,
        title: "Deep Meditation",
        desc: "Love, Wisdom, Awareness, Existence",
        pageName: "breathingActivity",
        improve: [{"awards_selfconfident": 1}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#6DA32F',
        gradientEnd: '#8DBD38',
        backgroundColor: '#608F2A',
    },
    lettersToYourSelf: {
        Icon: 'icon_week5',
        title: "Journal List",
        desc: "Write your today goal",
        pageName: 'journalEntry',
        improve: [{"Wisdom": 1}],
        gradientStart: "#8562f4",
        gradientEnd: "#7084f5",
        backgroundColor: '#E08D42',
    },
    didYouKnow: {
        Icon: 'icon_week3',
        title: "Did You Know You",
        desc: "Effect of pornography",
        pageName: 'didYouKnow',
        improve: [{"Wisdom": 1}],
        "gradientStart": "#387ece",
        "gradientEnd": "#49a3d8",
        backgroundColor: '#3270B2',
        improveData: ["awards_selfconfident"],
    },
    visualizationActivity: {
        Icon: 'icon_week2',
        title: "Visualize",
        desc: "Imagine a porn-free day",
        pageName: 'visualizationActivity',
        improve: [{"Dopamine": 1}],
        // "gradientStart": "#7284F7",
        // "gradientEnd": "#8561F6",
        "gradientStart": "#ec8b3c",
        "gradientEnd": "#f5be4b",
        "entryDate": 7,
        // backgroundColor: '#725ADC',
        backgroundColor: '#E08D42',
        improveData: ["award_braintrain"],
    },
    dailyDiscussion: {
        Icon: 'icon_week1',
        title: "Daily Discussion",
        desc: "Imagine a porn-free day",
        pageName: 'visualizationActivity',
        improve: [{"Dopamine": 1}],
        "gradientStart": "#7284F7",
        "gradientEnd": "#8561F6",
        "entryDate": 7,
        backgroundColor: '#725ADC',
        improveData: ["award_braintrain"],
    },
    stressRelief: {
        Icon: iconImage.StressIcon,
        title: "Stress Relief",
        desc: "Stay calm and in control",
        pageName: 'stressRelief',
        improve: [{"Stress": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    chooseYourPathActivity: {
        Icon: iconImage.pathIcon,
        title: "Choose Your Path",
        desc: "Remember what you want",
        pageName: 'chooseYourPathActivity',
        improve: [{"Wisdom": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    thoughtActivity: {
        Icon: iconImage.thoughtIcon,
        title: "Thought Control",
        desc: "Master your mind",
        pageName: 'thoughtActivity',
        improve: [{"Hypofrontality": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    protectDeviceActivity: {
        Icon: iconImage.protectIcon,
        title: "Protect Your Devices",
        desc: "Safeguard your phone",
        isIcon: false,
        pageName: '',
        improve: [],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    audioActivity: {
        Icon: iconImage.audioExercise,
        title: "Audio Exercise",
        desc: "Rewire your brain",
        pageName: 'audioActivity',
        improve: [{"Wisdom": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    brainActivity: {
        Icon: iconImage.BrainIcon,
        title: "Brain Training",
        desc: "Reprogram your brain",
        pageName: 'brainActivity',
        improve: [{"Dopamine": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    storyDetail: {
        Icon: iconImage.storyCardIcon,
        title: "Story",
        desc: "How life can change",
        pageName: 'storyDetail',
        improve: [{"Wisdom": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    kegalsActivity: {
        Icon: 'icon_week6',
        title: "Kegel Exercise",
        desc: "Pelvic floor muscle training",
        pageName: "kegalsActivity",
        improve: [{"awards_meditation": 3}, {"awards_selfconfident": 1}],
        improveData: ["awards_meditation", "awards_selfconfident"],
        gradientStart: '#ec8b3c',
        gradientEnd: '#f5be4b',
        backgroundColor: '#E08D42',
        isNew: true
    },
    emotionalActivity: {
        Icon: iconImage.EmotionalIcon,
        title: "Emotional Growth",
        desc: "Focus on real love",
        pageName: "emotionalActivity",
        improve: [{"Dopamine": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    faithActivity: {
        Icon: iconImage.FaithIcon,
        title: "Scripture",
        desc: "Faith and trust",
        pageName: "faithActivity",
        improve: [],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    journalActivity: {
        Icon: iconImage.JournalIcon,
        title: "Write In Your Journal",
        desc: "Externalize your thoughts",
        pageName: "journalActivity",
        improve: [],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    aboutYouActivity: {
        Icon: iconImage.rAboutYou,
        title: "About You",
        desc: "Complete your psychology profile",
        pageName: "aboutYouActivity",
        improve: [],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    internetFilterActivity: {
        Icon: iconImage.protectIcon,
        title: "Porn Blocker",
        desc: "Safe Browser In Safari",
        pageName: "internetFilterActivity",
        improve: [],
        gradientStart: '#387fce',
        gradientEnd: '#4aa5d8',
        backgroundColor: '#347BC3',
    },
    slipeMeditation: {
        Icon: iconImage.sleepIcon,
        title: "Sleep Meditation",
        desc: "Better sleep",
        pageName: "sleepMeditationController",
        improve: [],
        gradientStart: '#cc2b5e',
        gradientEnd: '#753a88',
        backgroundColor: '#7F524A',
    },
    notificationActivity: {
        Icon: iconImage.notificationIcon,
        title: "Enable Notifications",
        desc: "Team chat and milestones",
        pageName: "notificationsReminder",
        improve: [],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    monthlyChallenge: {
        Icon: iconImage.monthlyIcons[new Date().getMonth()],
        title: "Challenge",
        desc: "Go clean every day this month",
        pageName: "monthlyChallenge",
        improve: [],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    medicationActivity: {
        Icon: iconImage.MeditationIcon,
        title: "Meditation",
        desc: "Improve hypofrontality and self-control",
        pageName: "medicationActivity",
        improve: [{"meditation": 3}, {"selfconfident": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    }
};

const allMorningRoutine = {
    rMeditation: {
        icon: iconImage.rMeditation,
        name: "Meditation",
        endicon: '',
        pageName: 'medicationActivity',
        activityTime: 10,
        improve: [{"awards_meditation": 3}, {"awards_selfconfident": 1}],
        improveData: ["awards_meditation", "awards_selfconfident"],
        gradientStart: '#6DA32F',
        gradientEnd: '#8DBD38',
        backgroundColor: '#608F2A'
    },
    rExercise: {
        icon: iconImage.rBrainTraining,
        name: "Exercise",
        endicon: '',
        pageName: 'brainActivity',
        activityTime: 3,
        improve: [{"awards_selfconfident": 3}, {"award_braintrain": 1}],
        improveData: ["awards_selfconfident", "award_braintrain"],
        gradientStart: '#387ECE',
        gradientEnd: '#49A3D8',
        backgroundColor: '#3275BD',
    },
    gameActivity: {
        icon: iconImage.rGameYou,
        name: "Game",
        desc: "Complete your psychology profile",
        pageName: "gameActivity",
        improve: [{"award_braintrain": 3}],
        improveData: ["award_braintrain"],
        gradientStart: '#ed8f3d',
        gradientEnd: '#f3b648',
        backgroundColor: '#E78D25',
    },
    gamePowerMemory: {
        icon: iconImage.rGameYou,
        name: "Game",
        desc: "Complete your psychology profile",
        pageName: "gameActivity2",
        improve: [{"award_braintrain": 3}],
        improveData: ["award_braintrain"],
        gradientStart: '#ed8f3d',
        gradientEnd: '#f3b648',
        backgroundColor: '#E78D25',
    },
    rStory: {
        icon: iconImage.tMotivation,
        name: "Motivation",
        desc: "Complete your psychology profile",
        endicon: '',
        pageName: 'storyDetail',
        activityTime: 3,
        improve: [{"awards_selfconfident": 3}, {"award_braintrain": 4}],
        improveData: ["awards_selfconfident", "award_braintrain"],
        gradientStart: '#8562f4',
        gradientEnd: '#7084f5',
        backgroundColor: '#5F55F4'
    },
    rStory2: {
        icon: iconImage.tMotivation,
        name: "Inspirational story",
        desc: "Complete your psychology profile",
        endicon: '',
        pageName: 'storyDetail2',
        activityTime: 3,
        improve: [{"awards_selfconfident": 3}, {"award_braintrain": 4}],
        improveData: ["awards_selfconfident", "award_braintrain"],
        gradientStart: '#8562f4',
        gradientEnd: '#7084f5',
        backgroundColor: '#5F55F4'
    },
    rChoosePath: {
        icon: iconImage.rChoosePath,
        name: "What will you do",
        endicon: '',
        pageName: 'chooseYourPathActivity',
        activityTime: 1,
        improve: [{"awards_selfconfident": 3}],
        improveData: ["awards_selfconfident"],
        gradientStart: '#8562f4',
        gradientEnd: '#7083f5',
        backgroundColor: '#5F55F4',
    },
    audioActivity: {
        icon: iconImage.audioExercise,
        name: "Meditation audio",
        endicon: '',
        activityTime: 10,
        improve: [{"awards_meditation": 3}, {"awards_selfconfident": 1}],
        improveData: ["awards_meditation", "awards_selfconfident"],
        desc: "Rewire your brain",
        pageName: 'audioActivity',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    aboutYouActivity: {
        icon: iconImage.rAboutYou,
        name: "About You",
        desc: "Complete your psychology profile",
        pageName: "aboutYouActivity",
        improve: [],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    rThoughtControl: {
        icon: iconImage.rThoughtControl,
        name: "Thought control",
        endicon: '',
        pageName: 'thoughtActivity',
        activityTime: 2,
        improve: [{"Hypofrontality": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    rVisualize: {
        icon: iconImage.rVisualize,
        name: "Visualize",
        endicon: '',
        pageName: 'visualizationActivity',
        activityTime: 2,
        improve: [{"Dopamine": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    rStress: {
        icon: iconImage.rStress,
        name: "Stress relief",
        endicon: '',
        pageName: 'stressRelief',
        activityTime: 2,
        improve: [{"Stress": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    rEmotional: {
        icon: iconImage.rEmotional,
        name: "Emotional growth",
        endicon: '',
        pageName: 'emotionalActivity',
        activityTime: 2,
        improve: [{"Dopamine": 1}],
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
};

const awardApp = {
    lettersToYourSelf: {
        Icon: iconImage.letterIcon,
        title: "Write Your Letter",
        desc: "",
        pageName: 'lettersToYourSelf',
        improve: [{"Wisdom": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    stressRelief: {
        Icon: iconImage.StressIcon,
        title: "Stress Relief",
        desc: "Stay calm and in control",
        pageName: 'stressRelief',
        improve: [{"Stress": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    chooseYourPathActivity: {
        Icon: iconImage.pathIcon,
        title: "Choose Your Path",
        desc: "Remember what you want",
        pageName: 'chooseYourPathActivity',
        improve: [{"Wisdom": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    visualizationActivity: {
        Icon: iconImage.visualizationIcon,
        title: "Visualize",
        desc: "Imagine a porn-free day",
        pageName: 'visualizationActivity',
        improve: [{"Dopamine": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    thoughtActivity: {
        Icon: iconImage.thoughtIcon,
        title: "Thought Control",
        desc: "Master your mind",
        pageName: 'thoughtActivity',
        improve: [{"Hypofrontality": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    protectDeviceActivity: {
        Icon: iconImage.protectIcon,
        title: "Protect Your Devices",
        desc: "Safeguard your phone",
        isIcon: false,
        pageName: '',
        improve: [],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    audioActivity: {
        Icon: iconImage.audioExercise,
        title: "Audio Exercise",
        desc: "Rewire your brain",
        pageName: 'audioActivity',
        improve: [{"Wisdom": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    brainActivity: {
        Icon: iconImage.BrainIcon,
        title: "Brain Training",
        desc: "Reprogram your brain",
        pageName: 'brainActivity',
        improve: [{"Dopamine": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    storyDetail: {
        Icon: iconImage.storyCardIcon,
        title: "Story",
        desc: "How life can change",
        pageName: 'storyDetail',
        improve: [{"Wisdom": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    healthyActivity: {
        Icon: iconImage.activityIcon,
        title: "Healthy Activity",
        desc: "Positive dopamine release",
        pageName: 'healthyActivity',
        improve: [{"Dopamine": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    didYouKnow: {
        Icon: iconImage.DidyouknowIcon,
        title: "Did You Know?",
        desc: "The downside of pornography",
        pageName: 'didYouKnow',
        improve: [{"Wisdom": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
    breathingActivity: {
        Icon: iconImage.BreathingIcon,
        title: "Breathing Practice",
        desc: "Awareness and self-control",
        pageName: "breathingActivity",
        improve: [{"Stress": 1}],
        point: '+100',
        gradientStart: '#ED8C43',
        gradientEnd: '#F3B951',
        backgroundColor: '#E08D42',
    },
};

export {
    iconImage,
    allOptionalExercies,
    allMorningRoutine,
    notificationList,
    awardApp
};
