
//User Login Data Store
import {exp} from "react-native-reanimated";

export const APP_SET_USER_DATA = 'APP_SET_USER_DATA';

export const USER_EMAIL_CHANGED = 'USER_EMAIL_CHANGED';

export const USER_PASS_CHANGED = 'USER_PASS_CHANGED';
export const START_LOADING = 'START_LOADING';
export const USER_USERNAME_EDIT = 'USER_USERNAME_EDIT';
export const SET_SAFE_AREA_INTENT = 'SET_SAFE_AREA_INTENT';
export const SET_SAFE_AREA_INTENT_CHAT = 'SET_SAFE_AREA_INTENT_CHAT';
export const SET_SAFE_AREA_INTENT_X = 'SET_SAFE_AREA_INTENT_X';

export const SET_USER_TOKEN = 'SET_USER_TOKEN';

//Statistic details

export const SET_PORN_DAYS = 'SET_PORN_DAYS';
export const SET_M_DAYS = 'SET_M_DAYS';
export const MEDITATION_MINUTE = 'MEDITATION_MINUTE';
export const MEDITATION_M_CALCULATION = 'MEDITATION_M_CALCULATION';

export const STATISTIC_ALL_BACKUP='STATISTIC_ALL_BACKUP';
export const STATISTIC_ALL_BACKUP_EDIT = 'STATISTIC_ALL_BACKUP_EDIT';
export const STATISTIC_J_DATE_ARRAY = 'STATISTIC_J_DATE_ARRAY';
export const STATISTIC_JOURNAL_DETAIL_EDIT = 'STATISTIC_JOURNAL_DETAIL_EDIT';
export const STATISTIC_JOURNAL_DETAIL = 'STATISTIC_JOURNAL_DETAIL';
export const STATISTIC_OTHER_DETAIL = 'STATISTIC_OTHER_DETAIL';
export const STATISTIC_M_CALCULATION = 'STATISTIC_M_CALCULATION';
export const STATISTIC_P_CALCULATION = 'STATISTIC_P_CALCULATION';
export const STATISTIC_JOURNAL_TOTAL = 'STATISTIC_JOURNAL_TOTAL';

//Team Detail
export const TEAM_DETAIL = 'TEAM_DETAIL';

export const TEAM_MEMBER_ARRAY = 'TEAM_MEMBER_ARRAY';

export const TEAM_CHAT_MESSAGE_ARRAY = 'TEAM_CHAT_MESSAGE_ARRAY';

export const TEAM_CHAT_PAGINATION = 'TEAM_CHAT_PAGINATION';

export const INDIVIDUAL_LEADER_BOARD = 'INDIVIDUAL_LEADER_BOARD';

export const TEAM_LEADER_BOARD = 'TEAM_LEADER_BOARD';

export const TEAM_ACHIEVEMENT_DETAILS = 'TEAM_ACHIEVEMENT_DETAILS';

export const TEAM_MEMBER_EVENT_DETAILS = 'TEAM_MEMBER_EVENT_DETAILS';

export const TEAM__MEMBER_EVENT_PAGINATION_DETAILS = 'TEAM__MEMBER_EVENT_PAGINATION_DETAILS';

export const TEAM_LIST = 'TEAM_LIST';

export const TEAM__LIST_PAGINATION = 'TEAM__LIST_PAGINATION';

export const MEMBER_DETAIL = 'MEMBER_DETAIL';

export const SEEN_ACTIVITY_LIST = 'SEEN_ACTIVITY_LIST';

export const USER_EVENT_DETAILS = 'USER_EVENT_DETAILS';

export const USER_EVENT_PAGINATION_DETAILS = 'USER_EVENT_PAGINATION_DETAILS';

export const GLOBAL_STATISCTIC = 'GLOBAL_STATISCTIC';

export const SEEN_USER_EVENTS = 'SEEN_USER_EVENTS';

export const EVENT_BADGE_COUNT = 'EVENT_BADGE_COUNT';

export const START_EVENT_VIEWS = 'START_EVENT_VIEWS';

export const INVITE_LIST = 'INVITE_LIST';

export const INVITE_LIST_PAGINATION = 'INVITE_LIST_PAGINATION';

export const TEAM_LIST_SORT_TYPE = 'TEAM_LIST_SORT_TYPE';

export const TEAM_TODAY_MOTIVATION_DONE = 'TEAM_TODAY_MOTIVATION_DONE';

//Post Advice
export const ADVICE_POST_LIST = "ADVICE_POST_LIST";

export const ADVICE_PAGINATION_POST_LIST = "ADVICE_PAGINATION_POST_LIST";

export const ADD_ADVICE_DETAIL = "ADD_ADVICE_DETAIL";

export const ADVICE_SORT_TYPE = "ADVICE_SORT_TYPE";

export const ADVICE_POST_LIST_LIKED = "ADVICE_POST_LIST_LIKED";

export const ADVICE_POST_COMMENT_LIST = "ADVICE_POST_COMMENT_LIST";

export const ADVICE_COMMENT_PAGINATION_LIST = "ADVICE_COMMENT_PAGINATION_LIST";

//Help Post
export const HELP_POST_LIST = "HELP_POST_LIST";

export const HELP_PAGINATION_POST_LIST = "HELP_PAGINATION_POST_LIST";

export const HELP_POST_COMMENT_LIST = "HELP_POST_COMMENT_LIST";

export const HELP_POST_COMMENT_PAGINATION_LIST = "HELP_POST_COMMENT_PAGINATION_LIST";

export const ADD_HELP_DETAIL = "ADD_HELP_DETAIL";

export const HELP_SORT_TYPE = "HELP_SORT_TYPE";

export const ADD_FEED = 'ADD_FEED';

export const LIST_FEED = 'LIST_FEED';

export const LIST_FEED_ADVICE = 'LIST_FEED_ADVICE';

export const LIST_FEED_DAILY_DISCUSSION = 'LIST_FEED_DAILY_DISCUSSION';

export const LIST_FEED_MESSAGE_BOARD = 'LIST_FEED_MESSAGE_BOARD';

export const MY_FEED = 'MY_FEED';

export const OTHER_USER_FEED = 'OTHER_USER_FEED';

export const CATEGORY_FILTER = 'CATEGORY_FILTER';


//Current Rewiring Player
export const REWIRING_PLAY = "REWIRING_PLAY";

//MetaData
export const SET_META_DATA = "SET_META_DATA";

//Set visible tab
export const VISIBLE_TAB = "VISIBLE_TAB";

export const TOTAL_REWIRING_PERCENTAGE = "TOTAL_REWIRING_PERCENTAGE";

export const SET_REWIRING_BARS = "SET_REWIRING_BARS";

export const SET_LEVEL_DATA = "SET_LEVEL_DATA";

export const LEVEL_LIST = "LEVEL_LIST";

export const LEVEL_NUMBER = "LEVEL_NUMBER";

export const AWARD_LIST = "AWARD_LIST";

export const AWARD_TODAY = "AWARD_TODAY";

export const PORN_WHY_RELAPSE = "PORN_WHY_RELAPSE";

export const PORN_WHY_TEMPTED = "PORN_WHY_TEMPTED";

export const PORN_WHEN_TEMPTED = "PORN_WHEN_TEMPTED";

export const M_WHEN_TEMPTED = "M_WHEN_TEMPTED";

export const PORN_WHEN_RELAPSE = "PORN_WHEN_RELAPSE";

export const PORN_WHEN_STRESSED = "PORN_WHEN_STRESSED";

export const M_WHEN_RELAPSE = "M_WHEN_RELAPSE";

export const IMPROVEMEMT_PERCENTAGE = "IMPROVEMEMT_PERCENTAGE";

export const ADD_NEW_CHECKUP_QUESTION = "ADD_NEW_CHECKUP_QUESTION";

export const SET_USER_DETAIL = "SET_USER_DETAIL";

export const SET_MORNING_ROUTINE = "SET_MORNING_ROUTINE";

export const SET_DONE_MORNING_ROUTINE = "SET_DONE_MORNING_ROUTINE";

export const SET_GOAL_DATA = "SET_GOAL_DATA";

export const SET_CURRENT_USER_DATA = "SET_CURRENT_USER_DATA";

//Letters yourself
export const SET_LETTERS = "SET_LETTERS";

export const SET_LAST_LETTER_DAY = "SET_LAST_LETTER_DAY";

export const SET_LAST_LETTER_DATE = "SET_LAST_LETTER_DATE";

export const SET_COMPLETED_EXERCISES = "SET_COMPLETED_EXERCISES";

export const SET_SELECTED_OPTIONAL_EXERCISES = "SET_SELECTED_OPTIONAL_EXERCISES";

export const SETTING_NOTIFICATIONS = "SETTING_NOTIFICATIONS";

export const SETTING_TEAMCHAT_NOTIFICATIONS = "SETTING_TEAMCHAT_NOTIFICATIONS";

export const SHOW_CHECKUP_POPUP = "SHOW_CHECKUP_POPUP";

export const SHOW_TUTORIAL_POPUP = "SHOW_TUTORIAL_POPUP";

export const MANAGE_NOTIFICATION = "MANAGE_NOTIFICATION";
export const MANAGE_REWIRINGPROGRESS = "MANAGE_REWIRINGPROGRESS";
export const MANAGE_STREKPROGRESS = "MANAGE_STREKPROGRESS";
export const MANAGE_LEVELPROGRESS = "MANAGE_LEVELPROGRESS";
export const MANAGE_AWARDPROGRESS = "MANAGE_AWARDPROGRESS";

export const SET_RANDOMVARIBLE = "SET_RANDOMVARIBLE";

export const RATE_YOURDAY_3 = "RATE_YOURDAY_3";
export const RATE_YOURDAY_7 = "RATE_YOURDAY_7";
export const SERVER_DATE = "SERVER_DATE";

export const TUTORIAL_TAB1 = "TUTORIAL_TAB1";
export const TUTORIAL_TAB2 = "TUTORIAL_TAB2";
export const TUTORIAL_TAB3 = "TUTORIAL_TAB3";
export const TUTORIAL_TAB4 = "TUTORIAL_TAB4";

export const SHOW_REWIRING_POPUP = "SHOW_REWIRING_POPUP";

export const SHOW_UPDATE_CALENDAR_POPUP = "SHOW_UPDATE_CALENDAR_POPUP";

export const SHOW_MISSED_CHECKUP_POPUP = "SHOW_MISSED_CHECKUP_POPUP";

export const STREAK_GOAL_ACHIEVED_POPUP = "STREAK_GOAL_ACHIEVED_POPUP";

export const MANAGED_SHOW_STREAK_POPUP = "MANAGED_SHOW_STREAK_POPUP";

export const SHOW_STREAK_POPUP = "SHOW_STREAK_POPUP";

export const SHOW_REWIRING_PROGRESS_POPUP = "SHOW_REWIRING_PROGRESS_POPUP";

export const SET_READ_TODAY_LATTER = "SET_READ_TODAY_LATTER";

export const SET_API_CALL_DATE = "SET_API_CALL_DATE";

export const META_DATA_BACKUP = "META_DATA_BACKUP";

export const CUSTOM_POPUP = "CUSTOM_POPUP";

//Today instance
export const TODAY_INSTANCES = "TODAY_INSTANCES";

export const FIRST_TIME_APP_OPEN_IN_DAY = "FIRST_TIME_APP_OPEN_IN_DAY";

export const IS_ASK_FOR_CHECKUP = "IS_ASK_FOR_CHECKUP";

export const IS_NETWORK_AVAILABLE = "IS_NETWORK_AVAILABLE";

export const SUBSCRIPTION_CHECK_DATE = "SUBSCRIPTION_CHECK_DATE";

export const MEDITATION_TIME = "MEDITATION_TIME";

export const POPUP_QUEUE = "POPUP_QUEUE";

export const TODAY_SCREEN_EXERCISES = "TODAY_SCREEN_EXERCISES";

export const TODAY_EXERCISE = "TODAY_EXERCISE";

export const TODAY_LIFE_TREEE = "TODAY_LIFE_TREEE";

export const APP_BADGE_COUNT = "APP_BADGE_COUNT";

export const NOTIFICATION_BADGE_COUNT = "NOTIFICATION_BADGE_COUNT";

export const SELECT_THEME = "SELECT_THEME";

export const SELECT_THEME2 = "SELECT_THEME2";

export const DAILY_DISCUSSION = "DAILY_DISCUSSION";

export const ADMIN_LIST = "ADMIN_LIST";

export const INTERNET_FILTERSTATE = "INTERNET_FILTERSTATE";

export const REVENUECAYID = "REVENUECAYID";

export const REMEMBERPASSWORD = "REMEMBERPASSWORD";

export const INTERNET_FILTER = "INTERNET_FILTER";

export const APPTHEME_TYPE = "APPTHEME_TYPE";

export const RESET_STORE = "RESET_STORE";

export const SHOW_MONTHLY_POPUP = "SHOW_MONTHLY_POPUP";

export const SHOW_MONTHLY_CHALLENGE_POPUP = "SHOW_MONTHLY_CHALLENGE_POPUP";

export const MONTHLY_CHALLENGE_ACHIEVED = "MONTHLY_CHALLENGE_ACHIEVED";

export const ENCOURAGE_POPUP = "ENCOURAGE_POPUP";

export const CONGRATULATE_POPUP = "CONGRATULATE_POPUP";

export const TEAM_ACHIEVEMENTES = 'TEAM_ACHIEVEMENTES';

export const TEAM_ACHIEVEMENTES_PAGINATION = 'TEAM_ACHIEVEMENTES_PAGINATION';

export const TEAM_CHAT_DISPLAY_LIST = 'TEAM_CHAT_DISPLAY_LIST';

export const TEAM_CHAT_GET_MESSAGE = "TEAM_CHAT_GET_MESSAGE";

export const NOTIFICATION_LIST = 'NOTIFICATION_LIST';

export const NOTIFICATION_PROFILE = 'NOTIFICATION_PROFILE';

export const SET_DO_NOT_DISTURB = 'SET_DO_NOT_DISTURB';

export const SHOW_TEAM_ACHIEVEMENT_POPUP = "SHOW_TEAM_ACHIEVEMENT_POPUP";

export const LAST_TEAM_MESSAGE = "LAST_TEAM_MESSAGE";

export const SET_LOCATION_INFO = "SET_LOCATION_INFO";

export const USER_LEADERBOARD = "USER_LEADERBOARD";

export const PROFESSIONAL_USER_LIST = 'PROFESSIONAL_USER_LIST';

export const PROFESSIONAL_CHAT_MESSAGE_ARRAY = 'PROFESSIONAL_CHAT_MESSAGE_ARRAY';

export const PROFESSIONAL_CHAT_PAGINATION = 'PROFESSIONAL_CHAT_PAGINATION';

export const PROFESSIONAL_CHAT_DISPLAY_LIST = 'PROFESSIONAL_CHAT_DISPLAY_LIST';

export const PROFESSIONAL_USER_VISIBLE = "PROFESSIONAL_USER_VISIBLE";

//Traininig
export const TRAINING_LIST = "TRAINING_LIST";

//Traininig
export const SLEEP_MEDITATION_LIST = "SLEEP_MEDITATION_LIST";

export const PURCHASE_REGISTATION_DATA = "PURCHASE_REGISTATION_DATA";
