export const helpPostDefault = {
    helpPostList: [],
    isHelpPostSort: false,
    helpPostPagination: null,
    helpPostComment: [],
    helpPostCommentPagination: null,
    sortType: "hot",
    add: {},
    list: {},
    listPage: 0,
    getFeedStatus: true,
    listAdvice: {},
    listAdvicePage: 0,
    getFeedAdviceStatus: true,
    listDailyDiscussion: {},
    listDailyDiscussionPage: 0,
    getFeedDailyDiscussionStatus: true,
    listMessageBoard: {},
    listMessageBoardPage: 0,
    getFeedMessageBoardStatus: true,
    uplaodingAssest: false,
    myList: [],
    otherUserList: [],
    categoryFilter: 'Help',
    categorySubFilter: 'Recent',
    adminList: []
};
